en:
    archive.author: "Author"
    archive.authors: "Authors"
    archive.author_archive: "Author Archive"
    archive.category: "Category"
    archive.categories: "Categories"
    archive.category_archive: "Category Archive"
    archive.date: "Date"
    archive.dates: "Dates"
    archive.date_archive: "Date Archive"
    archive.year_archive: "Year Archive"
    archive.month_archive: "Month Archive"
    archive.week_archive: "Week Archive"
    archive.day_archive: "Day Archive"
    archive.tag: "Tag"
    archive.tags: "Tags"
    archive.tag_archive: "Tag Archive"
    archive.search: "Search"
    archive.pagination: "Page %1 of %2"

    carousel.previous: "Previous Slide"
    carousel.next: "Next Slide"

    page.404.title: "Error 404"
    page.404.subtitle: "Page not found"
    page.404.comment: "I'm sorry, but the page you're looking for was moved or doesn't exist."
    page.404.button: "Go back to the Homepage"
    page.error.title: "An error occured"
    page.error.subtitle: "Something bad happened"
    page.error.comment: "I'm sorry, but an error occured and destroyed everything."
    page.error.button: "Go back to the Homepage."
    page.maintenance.title: "Maintenance Mode"
    page.maintenance.description: "Sorry, we are down for maintenance but will be back in no time!"

    posts.preview: "Preview"
    posts.pending: "Pending"
    posts.no_thumbnail: "No Thumbnail available"
    posts.by_author: "by"
    posts.posted_in: "Posted In"
    posts.readmore: "Read More"
    posts.same_category: "from the same category"
    posts.widget.categories: "Browse Categories"
    posts.widget.latest: "Latest Articles"
    posts.widget.popular: "Popular Articles"
    posts.widget.random: "Random Articles"
    posts.widget.recent: "Recent Articles"
    posts.widget.similar: "Similar Articles"
    posts.widget.tags: "Browse Popular Tags"
    posts.empty.title: "I'm sorry"
    posts.empty.comment: "This archive does not contain any post yet."
    posts.empty.button: "Go back to the Homepage"
    posts.number_of_posts: "Number of Posts"
    posts.posts_in: "Posts since"
    posts.favourite_category: "Favourite Category"
    posts.posts_since: "Posts in"

    site.navbar.toggle: "Toggle Navigation"
    site.footer.socials: "Follow us on"
    site.widget.toc: "Table of Contents"
    site.widget.toc.goto: "Go To"

de:
    archive.author: "Autor"
    archive.authors: "Autoren"
    archive.author_archive: "Autorenarchiv"
    archive.category: "Kategorie"
    archive.categories: "Kategorien"
    archive.category_archive: "Kategorienarchiv"
    archive.date: "Datum"
    archive.dates: "Datum"
    archive.date_archive: "Datumsarchiv"
    archive.year_archive: "Jahresarchiv"
    archive.month_archive: "Monatsarchiv"
    archive.week_archive: "Wochenarchiv"
    archive.day_archive: "Tagesarchiv"
    archive.tag: "Schlagwort"
    archive.tags: "Schlagwörter"
    archive.tag_archive: "Schlagwortarchiv"
    archive.search: "Suche"
    archive.pagination: "Seite %1 von %2"

    carousel.previous: "Vorheriger Slice"
    carousel.next: "Nächster Slide"

    page.404.title: "Fehler 404"
    page.404.subtitle: "Seite nicht gefunden"
    page.404.comment: "Es tut mir leid, aber die Seite nach der du suchst wurde entweder verschoben oder existiert nicht."
    page.404.button: "Zurück zur Startseite"
    page.error.title: "Ein Fehler ist aufgetreten"
    page.error.subtitle: "Etwas schlimmes ist passiert"
    page.error.comment: "Es tut mir leid, aber ein Fehler ist aufgetreten und hat alles zerstört."
    page.error.button: "Zurück zur Startseite."
    page.maintenance.title: "Wartungsmodus"
    page.maintenance.description: "Es tut mir leid, aber aktuell warten wir unsere Webseite. Wir sind aber bald wieder für dich da!"

    posts.preview: "Vorschau"
    posts.pending: "Ausstehend"
    posts.no_thumbnail: "Kein Bild verfügbar"
    posts.by_author: "von"
    posts.posted_in: "Veröffentlicht in"
    posts.readmore: "Weiterlesen"
    posts.same_category: "von derselben Kategorie"
    posts.widget.categories: "Kateogrien durchsuchen"
    posts.widget.latest: "Aktuellste Beiträge"
    posts.widget.popular: "Beliebte Beiträge"
    posts.widget.random: "Zufällige Beiträge"
    posts.widget.recent: "Letzten Beiträge"
    posts.widget.similar: "Ähnliche Beiträge"
    posts.widget.tags: "Beliebte Schlagwörter durchsuchen"
    posts.empty.title: "Es tut mir Leid"
    posts.empty.comment: "Dieses Archiv enthält noch keine Beiträge."
    posts.empty.button: "Zurück zur Startseite"
    posts.number_of_posts: "Anzahl der Beiträge"
    posts.posts_in: "Beiträte seit"
    posts.favourite_category: "Beliebte Kategorie"
    posts.posts_since: "Beiträge in"

    site.navbar.toggle: "Navigation ein/ausblenden"
    site.footer.socials: "Folge und auf"
    site.widget.toc: "Inhaltsverzeichnis"
    site.widget.toc.goto: "Gehe zu"